### ISSUE TITLE
Volume calculation 

### ISSUE THREAD

**Issue by humanfr** [ccrause/syringepump#19]
There is a error when the stroke length is set to more than 60 mm 
It looks like the volume calculation is maxed out at 18.850 ml increasing the stroke length does not increase the available volume

**Comment by humanfr** [comment]
increasing the stroke length does however increase the slide travel accordingly

**Comment by humanfr** [comment]
for some rason the math is wrong when the stroke is defined at between 60+ and 70- even when using the defined values 
see debug messages below : 

PS C:\Users\Francois\github\syringepump> pio device monitor --port COM5 --baud 115200
--- Miniterm on COM5  115200,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
[1073480004:0,3,b2]
Full component reference: page0.b2
[1073479732:1,1,b0]
Full component reference: page1.b0
Reading settings from Nextion.
Get stroke from Nextion
recvRetNumber :65
Stroke = 65
Get speed% from Nextion

recvRetNumber :50
Speed = 50%
Get diameter from Nextion
recvRetString[6,20.000]
Diameter = 20.000000
Get volume from Nextion
recvRetString[2,20]
Volume = 20.000000
Get prime cycles from Nextion
recvRetNumber :1
Prime cycles = 1
Saving config
stroke: 65mm
strokePosLimit: 52000
recvRetCommandFinished ok
Speed = 20 mm/s
Ac: 3.142 cm^2
Syringe volume: 18.850
Dispense cycles: 2
recvRetCommandFinished ok
dispenseStroke = 25464

**Comment by humanfr** [comment]
here is the debug messages from using a stroke that is a factor of 10 
here the volume is calculated correctly 
i suspect the problem in the code has to do with the devision of the stroke lenght from mm to cm 

[1073480004:0,3,b2]
Full component reference: page0.b2
[1073479732:1,1,b0]
Full component reference: page1.b0
Reading settings from Nextion.
Get stroke from Nextion
recvRetNumber :60
Stroke = 60
Get speed% from Nextion
recvRetNumber :50
Speed = 50%
Get diameter from Nextion
recvRetString[6,20.000]
Diameter = 20.000000
Get volume from Nextion
recvRetString[2,20]
Volume = 20.000000
Get prime cycles from Nextion
recvRetNumber :1
Prime cycles = 1
Saving config
stroke: 60mm
strokePosLimit: 48000
recvRetCommandFinished ok
Speed = 20 mm/s
Ac: 3.142 cm^2
Syringe volume: 18.850
Dispense cycles: 2
recvRetCommandFinished ok
dispenseStroke = 25464

**Comment by humanfr** [comment]
Copied from code 
suspected problem 

uint32_t stroke;   // max travel distance mm[]
Chaged to float stroke

**Comment by ccrause** [comment]
Fixed by commit 8b158665013c9d333b86b615af9e56a49fb1e5b8. See also 6d60551ecbd2906d18be6d8c4e334a7ace8829f6 for more explicit casting during floating point calcs.
