### ISSUE TITLE
Syringe Zero Calibration 

### ISSUE THREAD

**Issue by humanfr** [ccrause/syringepump#20]
to ensure that the correct syringe zero point is probed and that the syringe is not seized move the syringe down 10 mm before probing up to the zero point

**Comment by ccrause** [comment]
This creates a potential complication when restarting controller with plunger at bottom.  Easy to recover if bottom limit switch is still used. Need some thought if we remove bottom limit switch.

Alternative idea may be to move up until trip, then back 10 mm.  If the second move trip then plunger is probably stuck.  This would not require a limit switch at the bottom.

**Comment by humanfr** [comment]
bottom limit switch will be retained, mechanical switch will be replaced with reed switch or magnetic alternative
