### ISSUE TITLE
errors after installing new PCB

### ISSUE THREAD

**Issue by humanfr** [ccrause/syringepump#26]
zero-point calibration does not work. tried a various encoder wheels current one is 20 line
encoder is not stopping the motor when it jams or is at a limit
speed for zero probe should be reduced so that the vibration does not cause false readings on the encoder 
the default config is not loaded to the nextion upon start up
updating the firmware requires several presses of the enable/boot button on the esp32
reset dispenser button on the screen is non responsive

**Comment by ccrause** [comment]
Hardware issues fixed.
