### ISSUE TITLE
Default Stroke length 

### ISSUE THREAD

**Issue by humanfr** [ccrause/syringepump#27]
Default stroke length for 20mL syringe is 65mm

**Comment by humanfr** [comment]
maxStroke length global variable (as a Volume)  added to nextion settings page to limit syringe travel input based on the syringe used in the config.
stroke lenght vairable to be changed from mm to volume

**Comment by ccrause** [comment]
Max stroke length based on ID & stated volume, so that the limit agrees with the last grade on the syringe.
