### ISSUE TITLE
Stroke Lenght Change

### ISSUE THREAD

**Issue by humanfr** [ccrause/syringepump#3]
if stroke length is changes on syringe that is primed and ready adjust plunger position when home is pressed 

as long as as the  valve is aligned to the inlet side the adjustment in plunger position should not matter

**Comment by ccrause** [comment]
Potentially solved by fix for issue #4.  Current behaviour for change in stroke length is no movement until dispense is pressed.  Then pump would move to new stroke limit before starting dispense cycle.

**Comment by ccrause** [comment]
See also #15
