### ISSUE TITLE
Nextion General 

### ISSUE THREAD

**Issue by humanfr** [ccrause/syringepump#6]
Display to be set to p0 by mcu once dispense button is pressed 
while dosing all other nextion input functions to be disabled 
config to be saved every time home button or dispense button is pressed, if possible only if a valid change is made 
statusText to only show Ready ,Dispense , Filling , Setup ,Prime or Error no other msgs allowed 
volume text to show calculated volume available in syringe at current position 
dispense volume can be shown it top line using errMsg0
switching between pages sometimes loses information in the various text fields these fields should be updated when scrolling between them fields of interest is statusText, volumeText, and slider0/1
nextion text items to be cleared of current build text

**Comment by ccrause** [comment]
I've broken up this issue into separate issues with one item of concern per issue for easier tracking.
